SGC.TaxClaims.WebUI/ViewModels/Claim/ClaimCreateModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGC.TaxClaims.WebUI.ViewModels
{
    /// <summary>
    /// View model для создания требования
    /// </summary>
    public class ClaimCreateModel
    {
        [DisplayName("Наименование инспекции")]
        [Description("Наименование инспекции")]
        public string InspectionName { get; set; }

        [DisplayName("Номер требования")]
        [Description("Номер требования")]
        [Required(ErrorMessage="Не заполнено поле \"Номер требования\"")]
        public string ClaimNumber { get; set; }

        [DisplayName("Предприятие-получатель")]
        [Description("Предприятие-получатель")]
        public int? OrgId { get; set; }

        [DisplayName("Комментарий")]
        [Description("Комментарий")]
        public string Comment { get; set; }

        [DisplayName("Срок подготовки ответа на требование")]
        [Description("Срок подготовки ответа на требование")]
        [UIHint("DateTimePicker")]
        public DateTime? DateReady { get; set; }

        /// <summary>
        /// Прикрепленные файлы
        /// </summary>
        public List<FileEditModel> Files { get; set; }

        /// <summary>
        /// Список предприятий-получателей требования.
        /// Инициализируется контроллером.
        /// </summary>
        public SelectList OrganizationSelectList { get; set; }

        public ClaimCreateModel()
        {
            Files = new List<FileEditModel>();
        }

        public void UpdateModel(SGC.TaxClaims.Core.Model.Claim model)
        {
            model.Number = this.ClaimNumber;
            model.Comment = this.Comment;
            model.InspectionName = this.InspectionName;
            model.Name = "";
            model.DateCreated = DateTime.UtcNow;
            model.DateReady = this.DateReady;
            model.OrgId = this.OrgId;
        }
    }
}

SGC.TaxClaims.WebUI/ViewModels/Claim/ClaimEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGC.TaxClaims.WebUI.ViewModels
{
    public class ClaimEditModel
    {
       [DisplayName("Наименование инспекции")]
        [Description("Наименование инспекции")]
        public string InspectionName { get; set; }

        [DisplayName("Номер требования")]
        [Description("Номер требования")]
        [Required(ErrorMessage="Не заполнено поле \"Номер требования\"")]
        public string ClaimNumber { get; set; }

        [DisplayName("Предприятие-получатель")]
        [Description("Предприятие-получатель")]
        public int? OrgId { get; set; }

        [DisplayName("Комментарий")]
        [Description("Комментарий")]
        public string Comment { get; set; }

        [DisplayName("Срок подготовки ответа на требование")]
        [Description("Срок подготовки ответа на требование")]
        [UIHint("DateTimePicker")]
        public DateTime? DateReady { get; set; }

        /// <summary>
        /// Прикрепленные файлы
        /// </summary>
        public List<FileEditModel> Files { get; set; }

        /// <summary>
        /// Список предприятий-получателей требования.
        /// Инициализируется контроллером.
        /// </summary>
        public SelectList OrganizationSelectList { get; set; }

        public ClaimEditModel()
        {
            Files = new List<FileEditModel>();
        }
    }
}

SGC.TaxClaims.WebUI/Controllers/ClaimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using SGC.TaxClaims.Common.Filtering;
using SGC.TaxClaims.Core;
using SGC.TaxClaims.Core.Model;
using SGC.TaxClaims.Infrastructure;
using SGC.TaxClaims.WebUI.AppCode;
using SGC.TaxClaims.WebUI.ViewModels;

namespace SGC.TaxClaims.WebUI.Controllers
{
    /// <summary>
    /// Контроллер требований
    /// </summary>
    public class ClaimController : BaseController
    {
        private IDBRepository _documentRepository;

        public ClaimController(IDBRepository documentRepository)
        {
            _documentRepository = documentRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Метод, к которому обращается Grid для загрузки данных
        /// </summary>
        /// <param name="gridSettings"></param>
        /// <returns></returns>
        public JsonResult GridData(MvcJqGrid.GridSettings gridSettings)
        {
            int pageSize = gridSettings.PageSize;
            int pageIndex = gridSettings.PageIndex - 1;
            string sortColumn = gridSettings.SortColumn;
            bool? asc = gridSettings.SortOrder == "asc";
            int totalRecords;

            FilterGroup filter = JqGridHelper.ParseFilter(gridSettings.Where);

            // TODO: [Петр] Check OperationResults
            OperationResult<PageResponse<Claim>> claims = _documentRepository.GetClaimsPage(pageSize, pageIndex, sortColumn, asc, filter, out totalRecords);

            return Json(
                new
                {
                    total = claims.Data.PagesCount,
                    page = claims.Data.PageIndex + 1,
                    records = claims.Data.RecordsCount,
                    rows = claims.Data.Rows
                        .OrderByDescending(claim => claim.DateReady)
                        .Select(claim => new ClaimIndexModel() {
                             Uid = claim.UId,
                             ClaimNumber = claim.Number,
                             Comment = claim.Comment,
                             InspectionName = claim.InspectionName,
                             Status = claim.DocState.DisplayName,
                             TargetOrganization = claim.Organization == null? string.Empty : claim.Organization.Name,
                             DateReady = claim.DateReady
                    })
                }
                , JsonRequestBehavior.AllowGet);

            //return new JsonResult()
            //{ Data = ""
            //   , JsonRequestBehavior = JsonRequestBehavior.AllowGet
            //};
        }

        [HttpGet]
        public ActionResult Create()
        {
            ClaimCreateModel viewModel = new ClaimCreateModel();

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(ClaimCreateModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            Claim claim = Claim.Create();
            viewModel.UpdateModel(claim);

            // ... Получение текущего пользователя
            OperationResult<aspnet_Users> currentUser = _documentRepository.GetUserByName(User.Identity.Name);

            // TODO: [Петр] Перенести в ModelConverter?
            // Инициализация документа
            claim.UId = Guid.NewGuid();
            claim.CreatorUserUid = currentUser.Data.UserId;

            // TODO: [Петр] Check OperationResult
            // ... Получение состояния документооборота, в который надо выставить документ при создании
            OperationResult<DocState> initialState = _documentRepository.GetInitialState(claim.DocTypeId, (int)DocumentRoute.ToIFNS);
            claim.DocStateId = initialState.Data.Id;

            // ... Получение состояния документоборота, в которое надо перевести документ после создания
            // TODO: [Петр] Check OperationResult
            OperationResult<DocState[]> nextStates = _documentRepository.GetNextPossibleStates(initialState.Data);

            // Присоединить файлы
            AttachFiles(claim, viewModel);

            // Сохранение документа
            claim.ChangeStatus = System.Data.Entity.EntityState.Added;
            // TODO: [Петр] Check ValidationInfo
            // TODO: [Петр] Добавь передачу идентификатора пользователя
            OperationResult<ValidationInfo[]> result = _documentRepository.SaveAndMove(claim, null, nextStates.Data[0].Id,Guid.Empty); // Передвигаем требование в следующее состояние

            return RedirectToAction("Index");
        }

        // TODO: [Петр] Перенести в ModelConverter?
        /// <summary>
        /// Прикрепление файлов к требованию
        /// </summary>
        /// <param name="claim"></param>
        /// <param name="viewModel"></param>
        private void AttachFiles(Claim claim, ClaimCreateModel viewModel)
        {
            foreach (var file in viewModel.Files)
            {
                if (!file.IsDeleted)
                {
                    DocFile docFile = DocFile.Create();
                    file.UpdateModel(docFile);
                    docFile.UId = Guid.NewGuid();
                    docFile.Content = System.IO.File.ReadAllBytes(file.SystemName);
                    docFile.ChangeStatus = System.Data.Entity.EntityState.Added;
                    docFile.DocumentUid = claim.UId;
                    docFile.FileTypeId = 1; // Unspecified
                    claim.DocFile.Add(docFile);
                }
            }
        }

        [HttpGet]
        public ActionResult Edit(Guid claimUid)
        {
            var operationResult = _documentRepository.GetClaimById(claimUid);
            //TODO: [Петр] тут нужно прописать вывод окна ошибки если операция завершенна не успешно
            var claim = operationResult.Data;
            ClaimEditModel model = new ClaimEditModel()
            {
                 ClaimNumber = claim.Number,
                 Comment = claim.Comment,
                 
                 InspectionName = claim.InspectionName
                 
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ClaimEditModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            return View();
        }

        [HttpGet]
        public ActionResult Details(Guid claimUid)
        {
            /*if (!ModelState.IsValid)
            {
                return View(viewModel);
            }*/
            var operationResult = _documentRepository.GetClaimById(claimUid);
            var claim = operationResult.Data;
            var operationResultRegistry = _documentRepository.GetRegistriesByClaimUid(claimUid);
            var registries = operationResultRegistry.Data;
            List<RegistryDisplayModel> registriesDisplay
                = registries.Select(registry => 
                    new RegistryDisplayModel()
                    {
                        Uid = registry.UId,
                        ClaimItemNo = registry.ClaimItemNo,
                        DateReady = registry.DateReady,
                        RegistryName = registry.Name,
                        UserCreator = registry.CreatorUser.UserName,
                        DateCreated = registry.DateCreated
                    })
                    .ToList();

            //TODO: [Петр] надо вставить оконо об ошибке
            ClaimViewModel claimViewModel = new ClaimViewModel()
            {
                ClaimNumber = claim.Number,
                Comment = claim.Comment,
                DateReady = claim.DateReady,
                InspectionName = claim.InspectionName,
                Organization = claim.Organization != null ? claim.Organization.Name : string.Empty,
                Registries = registriesDisplay
            };
            var getFileOperationResult = _documentRepository.GetDocumentFilesDiscritionOnly(claimUid);

            //TODO: [Петр] надо вставить оконо об ошибке
            claimViewModel.Files = getFileOperationResult.Data
                .Where(file => file.DocumentUid == claimUid)
                .Select(file => new FileViewModel() { UId = file.UId, Name = file.Name, TypeName = file.FileType.Name })
                .ToList();

            // Заполнение данных навигации
            ViewData["NavigationArea"] = new NavigationArea(new List<NavigationLink>()
            {
                new NavigationLink() { Title = "Требование", Tooltip = "Требование", Url = Url.Action("Details", "Claim", new { claimUid = claimUid}), IsActive = true },
                new NavigationLink() { Title = "Реестры", Tooltip = "Реестры", Url = Url.Action("ByClaim", "Registry", new { cid = claimUid}) }
            });

            return View(claimViewModel);
        }

        [HttpGet]
        public FileResult GetFile(Guid fid)
        {
            var operationResult = _documentRepository.GetFile(fid);
            var file = operationResult.Data;
            //TODO: [Петр] надо вставить оконо об ошибке
            return File(file.Content, System.Net.Mime.MediaTypeNames.Application.Octet, file.Name);
        }

        /// <summary>
        /// Переопределенный метод для загрузки в модели общих данных
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnResultExecuting(ResultExecutingContext filterContext)
        {
            base.OnResultExecuting(filterContext);

            // Модель создания требования дополнить списокм предприятий-получателей
            if (filterContext.Controller.ViewData.Model is ClaimCreateModel)
            {
                
                var model = (ClaimCreateModel)filterContext.Controller.ViewData.Model;

SGC.TaxClaims.WebUI/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SGC.TaxClaims.WebUI.ViewModels;

namespace SGC.TaxClaims.WebUI.Controllers
{
    public class FileController : Controller
    {
        private string UploadFolder { get { return Path.GetTempPath(); } }

        ////DONT USE THIS IF YOU NEED TO ALLOW LARGE FILES UPLOADS
        //[HttpGet]
        //public void Download(string id)
        //{
        //    var filename = id;
        //    var filePath = Path.Combine(Server.MapPath("~/Files"), filename);

        //    var context = HttpContext;

        //    if (System.IO.File.Exists(filePath))
        //    {
        //        context.Response.AddHeader("Content-Disposition", "attachment; filename=\"" + filename + "\"");
        //        context.Response.ContentType = "application/octet-stream";
        //        context.Response.ClearContent();
        //        context.Response.WriteFile(filePath);
        //    }
        //    else
        //        context.Response.StatusCode = 404;
        //}

        //DONT USE THIS IF YOU NEED TO ALLOW LARGE FILES UPLOADS
        [HttpPost]
        public ActionResult UploadFiles()
        {
            var r = new UploadFilesResult();

            //foreach (string file in Request.Files)
            //{
            int itemIndex = 0;
            Int32.TryParse(Request.Params["itemIndex"], out itemIndex);

                var statuses = new List<FileEditModel>();
                var headers = Request.Headers;

                if (string.IsNullOrEmpty(headers["X-File-Name"]))
                {
                    UploadWholeFile(Request, statuses);
                }
                else
                {
                    //UploadPartialFile(headers["X-File-Name"], Request, statuses);
                }

                //JsonResult result = Json(statuses);
                //result.ContentType = "text/plain";

                //return result;

            foreach(var status in statuses)
            {
                status.Index = itemIndex++;
                r.html.Add(MvcHelper.RenderPartialViewToString(ControllerContext, ViewData, TempData, "FileItem", status));
            }
            //}

            return Json(r);
        }

        //DONT USE THIS IF YOU NEED TO ALLOW LARGE FILES UPLOADS
        //Credit to i-e-b and his ASP.Net uploader for the bulk of the upload helper methods - https://github.com/i-e-b/jQueryFileUpload.Net
        private void UploadWholeFile(HttpRequestBase request, List<FileEditModel> statuses)
        {
            for (int i = 0; i < request.Files.Count; i++)
            {
                var file = request.Files[i];

                // Сгенерировать имя для файла - GUID
                string systemFileName = Guid.NewGuid().ToString();

                string fullPath = Path.Combine(UploadFolder, systemFileName);

                file.SaveAs(fullPath);

                statuses.Add(new FileEditModel()
                {
                    Name = file.FileName,
                    SystemName = fullPath,
                    Size = file.ContentLength,
                    Type = file.ContentType,
                    Url = "/File/Download?f=" + file.FileName,
                    UrlDelete = "/File/Delete?f=" + file.FileName,
                    //thumbnail_url = @"data:image/png;base64," + EncodeFile(fullPath),
                    //delete_type = "GET",
                });
            }
        }

        // TODO: [Петр] заглушка
        [HttpGet]
        public ActionResult Download(string f)
        {
            string fileName = Path.Combine(Path.GetTempPath(), f);

            Bitmap bmp = new Bitmap(fileName);

            bmp.Save(fileName + ".jpg", ImageFormat.Jpeg);

            return new FilePathResult(fileName + ".jpg", "image/jpeg");
        }

        private string EncodeFile(string fileName)
        {
            return Convert.ToBase64String(System.IO.File.ReadAllBytes(fileName));
        }
	}


}

SGC.TaxClaims.WebUI/Views/Claim/Create.cshtml
@model SGC.TaxClaims.WebUI.ViewModels.ClaimCreateModel

@{
    ViewBag.Title = "Новое требование";
}

<h2>Новое требование</h2>

@using (Html.BeginForm("Create", "Claim", FormMethod.Post, new { id = "formCreate" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        @Html.ValidationSummary(true)

        <table class="form">
            <thead>
                <tr>
                    <th/>
                    <th/>
                    <th/>
                    <th/>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="field-title">@Html.LabelFor(model => model.InspectionName)</td>
                    <td>@Html.EditorFor(model => model.InspectionName, new { htmlAttributes = new { @class="extended" } })</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.InspectionName)</td>
                </tr>
                <tr>
                    <td class="field-title">@Html.LabelFor(model => model.ClaimNumber)</td>
                    <td>@Html.EditorFor(model => model.ClaimNumber)</td>
                    <td><label class="required-field">*</label></td>
                    <td>@Html.ValidationMessageFor(model => model.ClaimNumber)</td>
                </tr>
                <tr>
                    <td class="field-title">@Html.LabelFor(model => model.OrgId)</td>
                    <td>@Html.DropDownListFor(model => model.OrgId, Model.OrganizationSelectList, new { @class="extended" })</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.OrgId)</td>
                </tr>
                <tr>
                    <td class="field-title">@Html.LabelFor(model => model.Comment)</td>
                    <td>@Html.TextAreaFor(model => model.Comment, new { @class="extended" })</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Comment)</td>
                </tr>
                <tr>
                    <td class="field-title">@Html.LabelFor(model => model.DateReady)</td>
                    <td>@Html.EditorFor(model => model.DateReady)</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.DateReady)</td>
                </tr>
            </tbody>
        </table>

        <div class="form-section">
            <h3 class="form-section-header">Приложенные документы</h3>

            <div class="form-section-content">
                <table class="list-container">
                    <tbody>
                        @for (int i = 0; i < Model.Files.Count; i++)
                        {
                            @Html.Partial("FileItem", Model.Files[i])
                        }
                        <tr id="anchorFiles"></tr>
                    </tbody>
                </table>
            </div>
            <div class="form-section-controls">
                <input id="fileupload" type="file" data-url="/File/UploadFiles">
            </div>
        </div>

        <div class="form-controls">
            <input type="submit" value="Создать" class="btn btn-primary" id="btn-submit" />
            @Html.ActionLink("Отмена", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
}

@*    <div id="fileupload">   
        @using (Html.BeginForm("UploadFiles", "File", FormMethod.Post, new { id = "formUploadFiles", enctype = "multipart/form-data" }))
        {
            <div class="fileupload-buttonbar">
                <label class="fileinput-button">
                    <span>Добавить файл...</span>
                    <input type="file" name="files[]" />
                </label>
            </div>      
        }

        <div class="fileupload-content">

            <div class="fileupload-progressbar"></div>
        </div>
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqfileupload")

    <script type="text/javascript">
        $(document).ready(function () {

            initControls();

            $("#btn-submit").click(function () {

                // Перед отправкой формы перенумеровать список файлов, чтобы не было совпадающих индексов
                SGC.Tax.Utils.reindexElementCollection($('.item-row'));
            });

            $('#fileupload').fileupload({
                dataType: 'json',

                done: function (e, data) {
                    $.each(data.result.html, function (index, renderedHtml) {
                        //$('<p/>').text(file.Name).appendTo(document.body);

                        $(renderedHtml).insertBefore("#anchorFiles");

                        onFileAdded();
                    });
                },
                send: function (e, data) {

                },
                submit: function (e, data) {
                    data.formData = { itemIndex: countFiles() };
                },
                fail: function (e, data) {
                    // data.errorThrown
                    // data.textStatus;
                    // data.jqXHR;
                    alert(data.textStatus + " : " + data.errorThrown);
                }
            });


        //    var validator1 = $("#formCreate").validate();
   
        //    $("#btn-submit").click(function () {

        //        if ($("#formCreate").valid()) {
        //            return true; // работает
        //        }
        //        return false;
               
        //    });   
        });

        function initControls(container) {
            // Связывание обработчиков событий

            if (typeof (container) !== 'undefined' && container != null) {
                $(".removeItem", container).click(onRemoveFile);
            }
            else {
                $(".removeItem").click(onRemoveFile);
            }
        }

        function onFileAdded() {
            initControls($('.item-row').last());
        }

        function onRemoveFile() {

            var item = $(this).closest('.item-row');
            $("input[name*='IsDeleted']", item).val('True'); // Пометить элемент удаленным
            item.hide();

            //$(this).closest('.item-row').remove();
            //reindexItems();
        }

        function countFiles() {
            return $('.item-row').size();
        }

    </script>
}

SGC.TaxClaims.WebUI/Views/Claim/Details.cshtml
@model SGC.TaxClaims.WebUI.ViewModels.ClaimViewModel
@{
    ViewBag.Title = "Просмотр требования";
}

@*<h2>Требование</h2>*@
@Html.Partial("_NavigationTitle", "Требование")

@Html.Partial("_NavigationArea")

    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <table class="form">
            <tbody>
                <tr>
                    <td>@Html.LabelFor(model => model.InspectionName)</td>
                    <td class="display-value">@Html.DisplayFor(model => model.InspectionName)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.ClaimNumber)</td>
                    <td class="display-value">@Html.DisplayFor(model => model.ClaimNumber)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Organization)</td>
                    <td class="display-value">@Html.DisplayFor(model => model.Organization)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.Comment)</td>
                    <td class="display-value">@Html.DisplayFor(model => model.Comment)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DateReady)</td>
                    <td class="display-value">@Html.DisplayFor(model => model.DateReady)</td>
                </tr>
            </tbody>
        </table>
        
        <div class="form-section">
            <h3 class="form-section-header">Файлы требования</h3>
            <div class="form-section-content">
            <table class="list-container">
                <tbody>
                    @for (int i = 0; i < Model.Files.Count; i++)
                    {
                        <tr>
                            <td>@Model.Files[i].Name</td>
                            <td><a title="Загрузить" href="/Claim/GetFile?fid=@Model.Files[i].UId"><i class="fa fa-file-image-o"></i></a></td>
                        </tr>
                    }
                </tbody>
            </table>
                </div>
        </div>

@*        @if (Model.Registries.Count != 0)
        {
            <div class="form-section">
                <h3 class="form-section-header">Реестры требования</h3>

                <div class="form-section-content">
                    <table class="list-container">
                        <thead>
                            <tr>
                                <th>Срок подготовки</th>
                                <th>Пункт требования</th>
                                <th>Наименование реестра</th>
                                <th>Дата создания</th>
                                <th>Кто создал</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Registries.Count; i++)
                            {
                                <tr>
                                    <td>@Model.Registries[i].DateReadyString</td>
                                    <td>@Model.Registries[i].ClaimItemNo</td>
                                    <td>@Model.Registries[i].RegistryName</td>
                                    <td>@Model.Registries[i].DateCreatedString</td>
                                    <td>@Model.Registries[i].UserCreator</td>
                                    <td><a title="Просмотр" href="/Registry/View?rid=@Model.Registries[i].Uid"><i class="fa fa-file-text-o"></i></a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        }*@

@*        <div class="form-controls">
            @Html.ActionLink("Закрыть", "Index","Claim", null, new { @class = "btn btn-primary"})
        </div>*@
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqfileupload")

    <script type="text/javascript">
        
    </script>
}

SGC.TaxClaims.WebUI/Views/Claim/Edit.cshtml
@model SGC.TaxClaims.WebUI.ViewModels.ClaimEditModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <h4>ClaimCreateModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <table class="form">
            <thead>
                <tr>
                    <th/>
                    <th/>
                    <th/>
                    <th/>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Html.LabelFor(model => model.InspectionName)</td>
                    <td>@Html.EditorFor(model => model.InspectionName)</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.InspectionName)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.ClaimNumber)</td>
                    <td>@Html.EditorFor(model => model.ClaimNumber)</td>
                    <td><label class="required-field">*</label></td>
                    <td>@Html.ValidationMessageFor(model => model.ClaimNumber)</td>
                </tr>
                @*<tr>
                    <td>@Html.LabelFor(model => model.TargetOrganization)</td>
                    <td>@Html.EditorFor(model => model.TargetOrganization)</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.TargetOrganization)</td>
                </tr>*@
                <tr>
                    <td>@Html.LabelFor(model => model.Comment)</td>
                    <td>@Html.EditorFor(model => model.Comment)</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.Comment)</td>
                </tr>
                <tr>
                    <td>@Html.LabelFor(model => model.DateReady)</td>
                    <td>@Html.EditorFor(model => model.DateReady)</td>
                    <td></td>
                    <td>@Html.ValidationMessageFor(model => model.DateReady)</td>
                </tr>
            </tbody>
        </table>
        <div class="form-group">
            <div class="col-md-offset-4 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку требований", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}